[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "https://acad.com.ng/web/kingdomsharon/:splat"
  status = 200
  force = true

# Also proxy API requests
[[redirects]]
  from = "/api/*"
  to = "https://acad.com.ng/ksps/api/:splat"
  status = 200
  force = true